### ISSUE TITLE
Discussion Section

### ISSUE THREAD

**Issue by MCUnderground** [LostTeam/Android-HtmlApp#1]
Discuss here:

**Comment by KyePlayzMCPE** [comment]
Hi

**Comment by eDroidPlayzYT** [comment]
hey um.. how big of a file is android studio? cuz u have to download the sdk and all that junk

**Comment by MCUnderground** [comment]
@eDroidPlayzYT android studio comes with sdk

**Comment by MCUnderground** [comment]
1.5gb max

I use to code on android. Using AIDE IDE

**Comment by eDroidPlayzYT** [comment]
eek lol I have a laptop that is 32 gigs and like 16 gigs is just the windows software. but I guess I can install it/download It on my flashdrive. right?

**Comment by MCUnderground** [comment]
Probably. I run windows 7 on android xD

**Comment by eDroidPlayzYT** [comment]
ill try downloading it sometime
